hydra:
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${run.dataset.name}
  sweep:
    dir: multirun
    # subdir: ${now:%Y-%m-%d}/${hydra.job.override_dirname}
    subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}
  launcher:
    # n_jobs: 8
    # n_jobs: 4
    n_jobs: 1
  
defaults:
  - run: mscoco_captions
  - override hydra/launcher: joblib

run:
  # data_path: /data/ailin/coco/
  seed: 0
  test_sample_num: 50
  device: 'cuda:0'
  tag: ''
task: 'generation' # 'eval'
force_rerun: False
resume: False